apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  selector:
    app: nodeService
  type: NodePort
  ports:
  - protocol: TCP
    name: port-react
    nodePort: 30001
    port: 80
  - protocol: TCP
    name: port-spring
    nodePort: 30002
    port: 9595
  - protocol: TCP
    name: port-actuator
    nodePort: 30003
    port: 1979  