apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-service-front
  template:
    metadata:
      labels:
        app: node-service-front
    spec:
      containers:
        - name: react-frontend
          image: devops-react-front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80